server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/01_springSecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver